// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['app']['API']['Cancel']();
}

export function CloseSend() {
  return window['go']['app']['API']['CloseSend']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['app']['API']['Connect'](arg1, arg2, arg3);
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['API']['DeleteWorkspace'](arg1);
}

export function ExportCommands(arg1, arg2, arg3) {
  return window['go']['app']['API']['ExportCommands'](arg1, arg2, arg3);
}

export function FindProtoFiles() {
  return window['go']['app']['API']['FindProtoFiles']();
}

export function GetMetadata(arg1) {
  return window['go']['app']['API']['GetMetadata'](arg1);
}

export function GetRawMessageState(arg1) {
  return window['go']['app']['API']['GetRawMessageState'](arg1);
}

export function GetReflectMetadata(arg1) {
  return window['go']['app']['API']['GetReflectMetadata'](arg1);
}

export function GetWorkspaceOptions() {
  return window['go']['app']['API']['GetWorkspaceOptions']();
}

export function ImportCommand(arg1, arg2) {
  return window['go']['app']['API']['ImportCommand'](arg1, arg2);
}

export function ListWorkspaces() {
  return window['go']['app']['API']['ListWorkspaces']();
}

export function RetryConnection() {
  return window['go']['app']['API']['RetryConnection']();
}

export function SelectDirectory() {
  return window['go']['app']['API']['SelectDirectory']();
}

export function SelectMethod(arg1, arg2, arg3) {
  return window['go']['app']['API']['SelectMethod'](arg1, arg2, arg3);
}

export function SelectWorkspace(arg1) {
  return window['go']['app']['API']['SelectWorkspace'](arg1);
}

export function Send(arg1, arg2, arg3) {
  return window['go']['app']['API']['Send'](arg1, arg2, arg3);
}
